version: "3.9"

services:
  master:
    build: .
    container_name: qaai_master
    command: python master/app.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always